CREATE TABLE t (x BIGINT);
INSERT INTO t VALUES (3), (1), (NULL), (2);
SELECT x FROM t ORDER BY x;
SELECT x FROM t ORDER BY x DESC;
SELECT x FROM t ORDER BY x LIMIT 2;
SELECT x FROM t ORDER BY x LIMIT 2 OFFSET 1;
SELECT x FROM t ORDER BY x OFFSET 3;
