CREATE TABLE orders (dept TEXT, amount BIGINT);
EXPLAIN SELECT dept, COUNT(*) FROM orders WHERE amount IS NOT NULL GROUP BY dept HAVING COUNT(*) > 1 ORDER BY dept LIMIT 5;
EXPLAIN SELECT DISTINCT dept FROM orders ORDER BY dept;
