CREATE TABLE t (name TEXT, id BIGINT);
INSERT INTO t VALUES ('b', 2), ('a', 1), ('c', 3);
SELECT name FROM t ORDER BY id;
EXPLAIN SELECT name FROM t ORDER BY id;
EXPLAIN SELECT id FROM t ORDER BY id;
SELECT DISTINCT name FROM t ORDER BY id;
